# Generated by Django 5.2 on 2025-04-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tourist_place',
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hotel',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.state')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='core.place'),
        ),
        migrations.DeleteModel(
            name='TouristPlace',
        ),
    ]
