# Generated by Django 5.2 on 2025-06-18 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_remove_review_upvotes_userpreference_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='visit',
            name='place',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='subject',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='travel_dates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='travelers',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
