# Generated by Django 5.2 on 2025-05-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hotel_place_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='entry_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='visiting_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text='Best months or seasons to visit the state.', max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='climate',
            field=models.TextField(blank=True, help_text='Climate information, including average temperatures and weather patterns.'),
        ),
        migrations.AddField(
            model_name='state',
            name='culture',
            field=models.TextField(blank=True, help_text='Cultural highlights, traditions, and festivals.'),
        ),
        migrations.AddField(
            model_name='state',
            name='history',
            field=models.TextField(blank=True, help_text='Historical background of the state.'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Historical', 'Historical'), ('Natural', 'Natural'), ('Beach', 'Beach'), ('Cultural', 'Cultural'), ('Adventure', 'Adventure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(blank=True, help_text='A general overview of the state.'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'place')},
            },
        ),
    ]
