# Generated by Django 5.2 on 2025-05-13 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_contact_created_at_hotel_price_per_night_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
