# Generated by Django 5.2 on 2025-05-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('activity', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='core.state')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
