# Generated by Django 5.2 on 2025-06-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
