# Generated by Django 5.2 on 2025-07-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_place_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
